# Generated by Django 4.2.7 on 2023-11-22 02:59

from django.db import migrations, models
import java_wallet.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerMonitor',
            fields=[
                ('announced_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('real_ip', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('height', models.PositiveIntegerField(blank=True, db_index=True)),
                ('cumulative_difficulty', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'online'), (2, 'unreachable'), (3, 'in sync'), (4, 'stuck'), (5, 'forked')], db_index=True)),
                ('downtime', models.PositiveIntegerField(blank=True, default=0)),
                ('lifetime', models.PositiveIntegerField(blank=True, default=0)),
                ('availability', models.FloatField(blank=True, default=0)),
                ('last_online_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reward_state', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('reward_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('block', models.IntegerField(primary_key=True, serialize=False)),
                ('generator_id', java_wallet.fields.PositiveBigIntegerField()),
                ('pool_id', java_wallet.fields.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'pool',
                'managed': True,
                'indexes': [models.Index(fields=['pool_id', '-block'], name='pool_pool_id_af57c1_idx')],
            },
        ),
    ]
