name: tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test
      run: |
        cp .env.default .env
        docker-compose build --build-arg APP_ENV=tests --build-arg UID="$UID"
        docker-compose run service coverage run ./manage.py test -v2
        docker-compose run service coverage report
        docker-compose run service coverage xml
    - name: Send coverage to Codacy
      env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        pip install codacy-coverage==1.3.11
        python-codacy-coverage -r ./coverage.xml
